---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    generation-date: 2018-03-12 08:17:13
  name: servicemonitors.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: ServiceMonitor
    plural: servicemonitors
  scope: Cluster
  validation:
    openAPIV3Schema: {}
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
